apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      annotations:
        openshift.io/quota-tier: Small
      labels:
        quota-tier: Small
      name: burst-quota
    spec:
      hard:
        pods: "9"
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      annotations:
        openshift.io/quota-tier: Small
      labels:
        quota-tier: Small
      name: quota
    spec:
      hard:
        pods: "6"
      scopes:
        - NotTerminating

